const vibeProjects = [
  {
    title: "World Cup",
    url: "./worldcup/",
    model: "opus 4.8",
    date: "jun 2026",
    note: "radial knockout bracket for every FIFA World Cup, 1930–2026, with live data from FIFA",
  },
  {
    title: "NutriHex",
    url: "./food/",
    model: "fable 5",
    date: "jun 2026",
    note: "FIFA-style stat hexagons for food — compare ingredients and meals, build dishes, personalize to your diet",
  },
  {
    title: "Keyfall",
    url: "./piano/",
    model: "fable 5",
    date: "jun 2026",
    note: "synthesia-style piano on your laptop keyboard — play or practice songs and get graded with tips",
  },
  {
    title: "Tech Riddles",
    url: "./tech-riddles/",
    model: "GPT 5.5",
    date: "may 2026",
    note: "poetry riddles for computer science major",
  },
  {
    title: "Tron: Cyber Cycles",
    url: "./tron/",
    model: "opus 4.6 and composer 2",
    date: "mar 2026",
    note: '3d arena game built on threejs, submitted to <a href="https://vibej.am/2026/" rel="noopener">vibejam/2026</a>',
  },
  {
    title: "Stick RPG",
    url: "./stick/",
    model: "opus 4.6",
    date: "apr 2026",
    note: "isometric stickman city RPG — built from a one-shot prompt",
  },
  {
    title: "Globe",
    url: "./globe/",
    model: "gemini 3.1 pro",
    date: "apr 2026",
    note: "interactive Three.js globe with country and city exploration",
  },
  {
    title: "Gas Log",
    url: "./gas/",
    model: "composer 2",
    date: "apr 2026",
    note: "gas fill-up tracker with cost and mileage stats",
  },
  {
    title: "Mindmap",
    url: "./mm/",
    model: "opus 4.6",
    date: "dec 2025–now",
    note: 'AI-native mindmap where every node is a prompt and every path is a conversation — now lives at <a href="https://mindmap.io" rel="noopener">mindmap.io</a>',
  },
  {
    title: "XO Game",
    url: "./xo/",
    model: "gemini 2.5 flash",
    date: "dec 2025",
    note: "infinite tic-tac-toe on an expandable board",
  },
  {
    title: "Drive",
    url: "./drive/",
    model: "",
    date: "apr 2026",
    note: "arcade racing game with garage car selector and city world",
    hidden: true,
  },
];
