// All game constants — devHud overrideable
export const CONFIG = {
    // World scale
    TILE_SIZE: 1,
    DEFAULT_ARENA_WIDTH: 400,
    DEFAULT_ARENA_DEPTH: 400,

    // Cycle mesh
    CYCLE_LENGTH: 0.8,
    CYCLE_WIDTH: 0.3,
    CYCLE_HEIGHT: 0.4,

    // Movement
    DEFAULT_TOP_SPEED: 60,
    DEFAULT_ACCELERATION: 20,
    CYCLE_FRICTION: 0.98,
    BRAKE_DECELERATION: 40,
    STEERING_SPEED_FALLOFF: 0.02,
    DEFAULT_HANDLING: 2.5,
    LOW_SPEED_THRESHOLD: 10,

    // Cycle animations
    CYCLE_TILT_MAX: 0.3,
    CYCLE_PITCH_ON_ACCEL: true,
    CYCLE_LEAN_ON_BRAKE: true,
    CYCLE_PITCH_AMOUNT: 0.08,
    CYCLE_LEAN_AMOUNT: 0.1,
    CYCLE_TILT_SPEED: 6.0,
    CYCLE_PITCH_SPEED: 5.0,

    // Camera
    CAMERA_DISTANCE: 8,
    CAMERA_HEIGHT: 4,
    CAMERA_LOOK_AHEAD: 3,
    CAMERA_DAMPING: 0.08,
    CAMERA_TURN_OFFSET: 1.5,
    CAMERA_FOV: 60,
    CAMERA_NITRO_FOV: 75,
    CAMERA_NITRO_PULL_BACK: 2,
    CAMERA_SHAKE_DECAY: 4.0,

    // Nitro
    NITRO_BARS: 5,
    NITRO_BURST_DURATION: 0.5,
    NITRO_SPEED_RETURN_TIME: 0.25,
    NITRO_MAX_SPEED_MULTIPLIER: 1.2,
    NITRO_BAR_RECHARGE_TIME: 5.0,
    NITRO_HANDLING_MULTIPLIER: 0.6,

    // Trail
    TRAIL_WALL_HEIGHT: 0.6,
    TRAIL_WALL_THICKNESS: 0.1,
    TRAIL_OPACITY: 0.8,
    TRAIL_MAX_SEGMENTS: 40,
    TRAIL_IMMUNITY_SEGMENTS: 4,

    // Arena visuals
    ARENA_WALL_HEIGHT: 3,
    GATE_WIDTH: 5,
    GRID_BRIGHTNESS: 0.8,
    NEON_INTENSITY: 1.0,
    FOG_DENSITY: 0.004,

    // Post-processing
    BLOOM_INTENSITY: 1.5,
    BLOOM_THRESHOLD: 0.3,
    CHROMATIC_ABERRATION: 0.002,

    // Colors
    PLAYER_COLOR: 0x00FFFF,
    ENEMY_COLOR: 0xFF6600,
    GRID_COLOR: 0x1a1a3e,
    BACKGROUND_COLOR: 0x0a0a0a,
};
